"""initial

Revision ID: 23b2a53ff851
Revises: 
Create Date: 2026-05-17 23:31:44.618896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23b2a53ff851'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dip_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('detected_date', sa.String(), nullable=False),
    sa.Column('trigger_date', sa.String(), nullable=False),
    sa.Column('change_pct_1d', sa.Float(), nullable=False),
    sa.Column('change_pct_5d', sa.Float(), nullable=True),
    sa.Column('macro_flag', sa.Integer(), nullable=False),
    sa.Column('macro_note', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('outcome_30d', sa.String(), nullable=True),
    sa.Column('outcome_note', sa.String(), nullable=True),
    sa.Column('extra_json', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'trigger_date', name='uq_dip_events_symbol_trigger_date')
    )
    op.create_index('idx_dip_events_detected_date', 'dip_events', ['detected_date'], unique=False)
    op.create_index('idx_dip_events_status', 'dip_events', ['status'], unique=False)
    op.create_table('index_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('change_pct', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', name='uq_index_prices_symbol_date')
    )
    op.create_table('stock_meta',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('market', sa.String(), nullable=False),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('sector_etf', sa.String(), nullable=True),
    sa.Column('index_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('meta_json', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('stock_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('adj_close', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', name='uq_stock_prices_symbol_date')
    )
    op.create_index('idx_stock_prices_symbol_date', 'stock_prices', ['symbol', 'date'], unique=False)
    op.create_table('briefings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dip_event_id', sa.Integer(), nullable=False),
    sa.Column('briefing_type', sa.String(), nullable=False),
    sa.Column('situation_summary', sa.String(), nullable=True),
    sa.Column('initial_class', sa.String(), nullable=True),
    sa.Column('initial_class_jp', sa.String(), nullable=True),
    sa.Column('accident_subtype', sa.String(), nullable=True),
    sa.Column('moat_json', sa.String(), nullable=True),
    sa.Column('counterarguments', sa.String(), nullable=True),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.Column('full_text', sa.String(), nullable=True),
    sa.Column('prompt_used', sa.String(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('generation_sec', sa.Float(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('is_latest', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dip_event_id'], ['dip_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_briefings_dip_event_id', 'briefings', ['dip_event_id'], unique=False)
    op.create_table('news_articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dip_event_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.String(), nullable=True),
    sa.Column('fetched_at', sa.String(), nullable=False),
    sa.Column('content_text', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('is_duplicate', sa.Integer(), nullable=False),
    sa.Column('before_trigger', sa.Integer(), nullable=True),
    sa.Column('extra_json', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dip_event_id'], ['dip_events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url', name='uq_news_articles_url')
    )
    op.create_index('idx_news_dip_event_id', 'news_articles', ['dip_event_id'], unique=False)
    op.create_index('idx_news_published_at', 'news_articles', ['published_at'], unique=False)
    op.create_table('numerical_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dip_event_id', sa.Integer(), nullable=False),
    sa.Column('volume_ratio_20d', sa.Float(), nullable=True),
    sa.Column('volatility_1y_sigma', sa.Float(), nullable=True),
    sa.Column('vol_deviation', sa.Float(), nullable=True),
    sa.Column('beta_1y', sa.Float(), nullable=True),
    sa.Column('sector_change_pct', sa.Float(), nullable=True),
    sa.Column('sector_relative', sa.Float(), nullable=True),
    sa.Column('sector_corr_90d', sa.Float(), nullable=True),
    sa.Column('per', sa.Float(), nullable=True),
    sa.Column('pbr', sa.Float(), nullable=True),
    sa.Column('equity_ratio', sa.Float(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('is_idiosyncratic', sa.Integer(), nullable=True),
    sa.Column('idiosyncratic_score', sa.Float(), nullable=True),
    sa.Column('analysis_json', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['dip_event_id'], ['dip_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_numerical_analyses_dip_event_id', 'numerical_analyses', ['dip_event_id'], unique=False)
    op.create_table('watchlist_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dip_event_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('added_date', sa.String(), nullable=False),
    sa.Column('trigger_price', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('closed_date', sa.String(), nullable=True),
    sa.Column('closed_reason', sa.String(), nullable=True),
    sa.Column('user_note', sa.String(), nullable=True),
    sa.Column('extra_json', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dip_event_id'], ['dip_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watchlist_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('watchlist_entry_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.String(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('recovery_pct', sa.Float(), nullable=False),
    sa.Column('volume_ratio', sa.Float(), nullable=True),
    sa.Column('new_news_count', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['watchlist_entry_id'], ['watchlist_entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('watchlist_entry_id', 'snapshot_date', name='uq_watchlist_snapshots')
    )
    op.create_index('idx_watchlist_snapshots_entry_id', 'watchlist_snapshots', ['watchlist_entry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_watchlist_snapshots_entry_id', table_name='watchlist_snapshots')
    op.drop_table('watchlist_snapshots')
    op.drop_table('watchlist_entries')
    op.drop_index('idx_numerical_analyses_dip_event_id', table_name='numerical_analyses')
    op.drop_table('numerical_analyses')
    op.drop_index('idx_news_published_at', table_name='news_articles')
    op.drop_index('idx_news_dip_event_id', table_name='news_articles')
    op.drop_table('news_articles')
    op.drop_index('idx_briefings_dip_event_id', table_name='briefings')
    op.drop_table('briefings')
    op.drop_index('idx_stock_prices_symbol_date', table_name='stock_prices')
    op.drop_table('stock_prices')
    op.drop_table('stock_meta')
    op.drop_table('index_prices')
    op.drop_index('idx_dip_events_status', table_name='dip_events')
    op.drop_index('idx_dip_events_detected_date', table_name='dip_events')
    op.drop_table('dip_events')
    # ### end Alembic commands ###
